# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d8573628647a2d2414397dd51c10554ea58a43f983dde39bd4ed7e41eab3ac501c981821e6ae751b165b3932ba98e8fb8c7ed9ef38cff39930f6562604c6336

test:
  secret_key_base: d443dbb8769fd062091ed22c9ca4a207cd4dc0ceee3b9e87f826a80ed07ae9712c33acd139cef812a01d7ef90da8eabb02799b172f1f02ecdd8eeedacc5280b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
